#!/bin/sh

#    This file is part of ios-mount.
#
#    ios-mount is free software: you can redistribute it and/or modify it under
#    the terms of the GNU General Public License as published by the
#    Free Software Foundation, either version 3 of the License, or (at your
#    option) any later version.
#
#    ios-mount is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see https://www.gnu.org/licenses/.

# Defaults
lines=2
border="$DMENU_BORDER"
height="$DMENU_HEIGHT"
prompt="󰄠 iOS Mounter:"

# List of choices 
list_choices(){
	cat << EOF
󰄟 Mount
󰮑 Eject
EOF
}

# dmenu command
dmenu_cmd(){
	dmenu -c -n -l "$lines" -bw "$border" -h "$height" -p "$prompt"
}

choice=$(list_choices | dmenu_cmd)

case "$choice" in
	"󰄟 Mount") ios-mount mount ;;
 	"󰮑 Eject") ios-mount unmount ;;
esac



# vim: ft=sh
