#!/bin/sh

#    This file is part of ios-mount.
#
#    ios-mount is free software: you can redistribute it and/or modify it under
#    the terms of the GNU General Public License as published by the
#    Free Software Foundation, either version 3 of the License, or (at your
#    option) any later version.
#
#    ios-mount is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see https://www.gnu.org/licenses/.

# This script mounts iOS devices to $IOS_MOUNTPOINT

# Set the default if the variable is not set
[ -z "$IOS_MOUNTPOINT" ] && IOS_MOUNTPOINT="$HOME/iOS"

# Mount
mount() {
	mkdir -p "$IOS_MOUNTPOINT"
	ifuse "$IOS_MOUNTPOINT" && notify-send -u low -i phone "iOS Mounter" "Your iOS device has been successfully mounted to $IOS_MOUNTPOINT" || (notify-send -u critical -i phone "iOS Mounter" "Failed to mount your device. Make sure it is connected properly" && rm -rf "$IOS_MOUNTPOINT")
}

# Unmount
unmount() {
	fusermount -u "$IOS_MOUNTPOINT" && rm -rf "$IOS_MOUNTPOINT" && notify-send -u low -i phone "iOS Mounter" "Your iOS device has been successfully ejected from $IOS_MOUNTPOINT" || notify-send -u critical -i phone "iOS Mounter" "There is no device mounted at $IOS_MOUNTPOINT"
}

# Help 
help() {
	cat << EOF
ios-mount

Usage: 
	ios-mount [COMMAND]
	[ENVIRONMENT VARIABLES..] ios-mount [COMMAND]

Commands:
	mount:		Mount your iOS device to $IOS_MOUNTPOINT
	unmount:	Unmount your iOS device from $IOS_MOUNTPOINT
	help:		Display this help and exit

Environment variables:
	IOS_MOUNTPOINT (string):	The directory where the iOS device will be mounted
EOF
}

not_exist() {
	printf " \n"
	help
	exit 1
}

# If the command entered does not exist, display help and exit with an error
[ -n "$1" ] && $1 || not_exist



# vim: ft=sh
